### ISSUE TITLE
Doesn't work with v22.x

### ISSUE THREAD

**Issue by stef-pellegrino** [xianlinzhang/smartgit-crack#3]
any idea ?

**Comment by yangweijie** [comment]
smartgit-agent 好像win下不好使 我mac一直用的

**Comment by xianlinzhang** [comment]
可以申请一个非商业的li

**Comment by xianlinzhang** [comment]
@stef-pellegrino @yangweijie   可以申请一个非商业的License

[https://www.syntevo.com/register-non-commercial/](url)
